default:
  image: ${DOCKER_IMAGE}

stages:
  - build

build-code:
  stage: build
  script:
    - wget -m --cut-dirs 4 --level 0 --no-parent "https://${SERVER}/${COURSE}/${SECRET}/ci" > /dev/null 2>&1
    - cd ${SERVER} && python3 ci.py
  rules:
    - when: manual
